site_name: humera

theme:
  features:
    - navigation.path
  name: material
  logo: assets/logo.svg
  palette:


    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      background: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: yellow
      background: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode